BANCO_PALAVRAS = {
    "Comidas": [
        ("Pizza", "Fatia"), ("Hambúrguer", "Pão"), ("Sushi", "Cru"), ("Lasanha", "Camadas"),
        ("Churrasco", "Brasa"), ("Tacos", "Crosta"), ("Cachorro Quente", "Salsicha"),
        ("Batata Frita", "Óleo"), ("Salada", "Folhas"), ("Sopa", "Caldo"),
        ("Macarrão", "Fios"), ("Arroz", "Grãos"), ("Feijão", "Caldo"),
        ("Bife", "Chapa"), ("Omelete", "Ovos"), ("Queijo", "Cura"),
        ("Bolo", "Festa"), ("Sorvete", "Cone"), ("Chocolate", "Cacau"),
        ("Pipoca", "Estouro"), ("Coxinha", "Fritura"), ("Pastel", "Feira"),
        ("Açaí", "Roxo"), ("Strogonoff", "Creme"), ("Panqueca", "Frigideira"),
        ("Ameixa", "Roxa"), ("Amora", "Fruta"), ("Mirtilo", "Pequeno"), ("Tangerina", "Gomos"),
        ("Caju", "Suco"), ("Caqui", "Doce"), ("Carambola", "Estrela"), ("Jabuticaba", "Tronco"),
        ("Pitanga", "Vermelha"), ("Tamarindo", "Azedo"), ("Graviola", "Branca"), ("Cupuaçu", "Amazônia"),
        ("Romã", "Sementes"), ("Nectarina", "Pele"), ("Damasco", "Seco"), ("Rabanete", "Raiz"),
        ("Beterraba", "Sangue"), ("Inhame", "Sopa"), ("Quiabo", "Baba"), ("Chuchu", "Água"),
        ("Jiló", "Amargo"), ("Repolho", "Folhas"), ("Rúcula", "Amarga"), ("Agrião", "Verde"),
        ("Escarola", "Refogada"), ("Alcachofra", "Coração"), ("Aspargo", "Fino"), ("Palmito", "Torta"),
        ("Mandioquinha", "Creme"), ("Pinhão", "Inverno"), ("Cogumelo", "Fungo"), ("Erva-doce", "Chá"),
        ("Sonho", "Padaria"), ("Rocambole", "Enrolado"), ("Alfajor", "Doce"), ("Macaron", "Francês"),
        ("Cupcake", "Bolinho"), ("Muffin", "Massa"), ("Petit Gâteau", "Quente"), ("Profiterole", "Creme"),
        ("Pão de Mel", "Cobertura"), ("Suspiro", "Leve"), ("Maria-mole", "Macia"), ("Doce de Leite", "Colher"),
        ("Cocada", "Raspada"), ("Paçoca", "Esfarela"), ("Pé de Moleque", "Duro"), ("Cajuzinho", "Festa"),
        ("Baba de Moça", "Calda"), ("Manjar", "Ameixa"), ("Ambrosia", "Fios"), ("Sagu", "Bolinhas"),
        ("Arroz Doce", "Canela"), ("Rabanada", "Pão"), ("Goiabinha", "Biscoito"), ("Marshmallow", "Fogueira"),
        ("Bobó", "Creme"), ("Tacacá", "Tigela"), ("Maniçoba", "Folha"), ("Baião de Dois", "Mistura"),
        ("Tutu", "Engrossado"), ("Galinhada", "Frango"), ("Salpicão", "Frio"), ("Empadão", "Forno"),
        ("Fricassê", "Batata"), ("Picadinho", "Cubos"), ("Almôndega", "Bolota"), ("Salsicha", "Cachorro"),
        ("Linguiça", "Grelha"), ("Calabresa", "Fatiada"), ("Pepperoni", "Apimentado"), ("Bisteca", "Osso"),
        ("Picanha", "Corte"), ("Costela", "Assado"), ("Maminha", "Carne"), ("Alcatra", "Churrascaria"),
        ("Fraldinha", "Fibras"), ("Cupim", "Gordura"), ("Lombo", "Suíno"), ("Tender", "Fim-de-ano"),
        ("Carré", "Cordeiro"), ("Vitela", "Maciez"), ("Marreco", "Ave"), ("Codorna", "Pequena"),
        ("Polvo", "Tentáculos"), ("Lula", "Anéis"), ("Ostra", "Concha"), ("Mexilhão", "Marisco"),
        ("Siri", "Casca"), ("Anchova", "Sal"), ("Sardinha", "Lata"), ("Atum", "Pedaço"),
        ("Salmão", "Japonês"), ("Bacalhau", "Gomes"), ("Trigo", "Farinha"), ("Aveia", "Mingau"),
        ("Quinoa", "Saudável"), ("Torrada", "Manteiga"), ("Bolacha", "Pacote"), ("Biscoito", "Chá")
    ],
    
    "Animais": [
        ("Cachorro", "Coleira"), ("Gato", "Caixa"), ("Leão", "Juba"), ("Tigre", "Listras"),
        ("Urso", "Caverna"), ("Lobo", "Uivo"), ("Raposa", "Astúcia"), ("Elefante", "Tromba"),
        ("Girafa", "Pescoço"), ("Zebra", "Listras"), ("Macaco", "Árvore"), ("Canguru", "Bolsa"),
        ("Panda", "Bambu"), ("Cavalo", "Sela"), ("Vaca", "Pasto"), ("Porco", "Lama"),
        ("Ovelha", "Lã"), ("Galinha", "Grama"), ("Pato", "Lago"), ("Coruja", "Noite"),
        ("Pinguim", "Gelo"), ("Sapo", "Pulo"), ("Tartaruga", "Casco"), ("Cobra", "Veneno"),
        ("Tubarão", "Dentes"), ("Baleia", "Oceano"), ("Aranha", "Teia"), ("Abelha", "Mel"),
        ("Hipopótamo", "Boca"), ("Rinoceronte", "Chifre"), ("Gorila", "Peito"), ("Chimpanzé", "Primata"),
        ("Coala", "Eucalipto"), ("Camelo", "Corcova"), ("Cabra", "Montanha"), ("Burro", "Carga"),
        ("Touro", "Chifres"), ("Búfalo", "Manada"), ("Alce", "Galhada"), ("Rena", "Neve"),
        ("Ganso", "Grasna"), ("Peru", "Natal"), ("Pombo", "Cidade"), ("Corvo", "Preto"),
        ("Águia", "Visão"), ("Falcão", "Rapina"), ("Papagaio", "Fala"), ("Arara", "Colorida"),
        ("Tucano", "Bico"), ("Avestruz", "Corre"), ("Pavão", "Penas"), ("Cisne", "Elegante"),
        ("Gaivota", "Praia"), ("Pelicano", "Bolsa"), ("Cegonha", "Bebê"), ("Flamingo", "Rosa"),
        ("Rã", "Pântano"), ("Perereca", "Parede"), ("Crocodilo", "Réptil"), ("Jacaré", "Lagoa"),
        ("Jabuti", "Lento"), ("Lagarto", "Rabo"), ("Iguana", "Verde"), ("Camaleão", "Cor"),
        ("Dragão-de-Komodo", "Bactéria"), ("Golfinho", "Acrobata"), ("Foca", "Equilíbrio"), ("Leão-Marinho", "Bigode"),
        ("Morsa", "Presas"), ("Peixe", "Água"), ("Salmão", "Rio"), ("Atum", "Mar"),
        ("Bacalhau", "Salgado"), ("Sardinha", "Cardume"), ("Carpa", "Japão"), ("Peixe-Palhaço", "Anêmona"),
        ("Cavalo-Marinho", "Oceano"), ("Polvo", "Oito"), ("Lula", "Tinta"), ("Água-Viva", "Queima"),
        ("Estrela-do-Mar", "Pontas"), ("Caranguejo", "Lado"), ("Lagosta", "Cara"), ("Camarão", "Frito"),
        ("Ostra", "Pérola"), ("Marisco", "Rocha"), ("Caracol", "Gosma"), ("Lesma", "Sal"),
        ("Minhoca", "Terra"), ("Sanguessuga", "Sangue"), ("Escorpião", "Ferrão"), ("Formiga", "Trabalho"),
        ("Vespa", "Ferroa"), ("Mosca", "Lixo"), ("Mosquito", "Dengue"), ("Borboleta", "Casulo"),
        ("Mariposa", "Lâmpada"), ("Besouro", "Casca"), ("Barata", "Esgoto"), ("Lontra", "Brincalhona"),
        ("Castor", "Represa"), ("Capivara", "Tranquila"), ("Tamanduá", "Formigueiro"), ("Bicho-Preguiça", "Sono"),
        ("Tatu", "Bola"), ("Suricato", "Sentinela"), ("Leopardo", "Veloz"), ("Guepardo", "Corrida"),
        ("Lhama", "Cuspe"), ("Orca", "Assassina"), ("Peixe-Boi", "Gordo"), ("Beija-Flor", "Pequeno"),
        ("Canário", "Canto"), ("Toupeira", "Cega"), ("Ouriço", "Espinhos"), ("Hiena", "Risada"),
        ("Chacal", "Carniceiro"), ("Pantera", "Negra"), ("Javali", "Selvagem"), ("Antílope", "Savana"),
        ("Hámster", "Gaiola"), ("Porquinho-da-Índia", "Roedor"), ("Cobaia", "Laboratório"), ("Chinchila", "Gordinho"),
        ("Furão", "Fofo"), ("Bicho-da-Seda", "Fio"), ("Joaninha", "Pontinhas"), ("Gafanhoto", "Pulo")
    ],
    
    "Marcas Famosas": [
        ("Coca-Cola", "Vermelho"), ("Pepsi", "Azul"), ("Apple", "Maçã"), ("Samsung", "Coreia"),
        ("Microsoft", "Janelas"), ("Google", "Busca"), ("Amazon", "Entregas"), ("Netflix", "Streaming"),
        ("Disney", "Castelo"), ("McDonald's", "Amarelo"), ("Burger King", "Coroa"),
        ("Nike", "Esportes"), ("Adidas", "Listras"), ("Ferrari", "Cavalo"), ("Porsche", "Escudo"),
        ("Volkswagen", "Círculo"), ("Rolex", "Relógio"), ("Gucci", "Grife"), ("Zara", "Roupas"),
        ("Sony", "Videogame"), ("Nintendo", "Jogos"), ("Lego", "Blocos"), ("Red Bull", "Energético"),
        ("Heineken", "Verde"), ("Uber", "Carona"), ("Spotify", "Música"),
        ("Intel", "Processador"), ("Motorola", "Celular"), ("Nokia", "Tijolão"), ("HP", "Impressora"),
        ("Chevrolet", "Gravata"), ("Honda", "Motos"), ("Fiat", "Uno"), ("KFC", "Balde"),
        ("Domino's", "Pizzaria"), ("Taco Bell", "Sino"), ("Ray-Ban", "Óculos"), ("Oakley", "Esportivo"),
        ("Vans", "Skate"), ("Converse", "Estrela"), ("Balenciaga", "Cara"), ("Dior", "Elegância"),
        ("Gatorade", "Isotônico"), ("Hulu", "Séries"), ("HBO", "Canal"), ("Oreo", "Biscoito"),
        ("Puma", "Felino"), ("Louis Vuitton", "Bolsas"), ("Prada", "Diabo"), ("Chanel", "Número"),
        ("L'Oréal", "Beleza"), ("Gillette", "Barbear"), ("Colgate", "Dentes"), ("Pampers", "Fraldas"),
        ("PlayStation", "Console"), ("Xbox", "Caixa"), ("Mattel", "Boneca"), ("Hasbro", "Tabuleiro"),
        ("Budweiser", "Cerveja"), ("Nescafé", "Solúvel"), ("Starbucks", "Sereia"), ("Nestlé", "Pássaro"),
        ("Visa", "Crédito"), ("Mastercard", "Bolinhas"), ("PayPal", "Online"), ("Toyota", "Japonesa"),
        ("BMW", "Alemã"), ("Casio", "Calculadora"), ("Instagram", "Fotos"), ("TikTok", "Vídeos"),
        ("WhatsApp", "Mensagem"), ("Facebook", "Rede"), ("Twitter", "Passarinho"), ("LinkedIn", "Emprego"),
        ("YouTube", "Play"), ("Twitch", "Roxa"), ("Airbnb", "Hospedagem"), ("iFood", "Entrega"),
        ("Rappi", "Comida"), ("Mercado Livre", "Amarelo"), ("Shopee", "Pacotes"), ("AliExpress", "Barato"),
        ("Shein", "Desconto"), ("Magalu", "Loja"), ("Avon", "Cabelo"), ("Natura", "Catálogo"),
        ("Boticário", "Essência"), ("Havaianas", "Chinelo"), ("Crocs", "Furos"), ("Asics", "Corrida"),
        ("Reebok", "Calçado"), ("Fila", "Esporte"), ("Michelin", "Pneu"), ("Pirelli", "Borracha"),
        ("Goodyear", "Dirigir"), ("Yamaha", "Motor"), ("Suzuki", "Teclado"), ("Kawasaki", "Moto"),
        ("Harley-Davidson", "Chopper"), ("Jeep", "Trilha"), ("Nissan", "Carro"), ("Hyundai", "Coreana"),
        ("Peugeot", "Leão"), ("Renault", "Losango"), ("Audi", "Argolas"), ("Mercedes-Benz", "Luxo"),
        ("Volvo", "Caminhão"), ("Heinz", "Catchup"), ("Hellmann's", "Maionese"), ("Doritos", "Salgadinho"),
        ("Ruffles", "Ondulada"), ("Cheetos", "Salgado"), ("Pringles", "Batata"), ("M&M's", "Confeitos"),
        ("Snickers", "Amendoim"), ("KitKat", "Wafer"), ("Twix", "Caramelo"), ("Toblerone", "Suíço"),
        ("Lindt", "Chocolate"), ("Ferrero Rocher", "Bombom"), ("Nutella", "Creme"), ("Kellogg's", "Sucrilhos"),
        ("Bauducco", "Panetone"), ("Lacta", "Ovo"), ("Garoto", "Amarelo")
    ],
    
    "Desenhos Famosos": [
        ("Bob Esponja", "Mar"), ("Os Simpsons", "Amarelos"), ("Pica-Pau", "Pássaro"),
        ("Tom e Jerry", "Perseguição"), ("Scooby-Doo", "Mistério"), ("Dragon Ball Z", "Esferas"),
        ("Naruto", "Ninjas"), ("Pokémon", "Captura"), ("Os Flintstones", "Pedra"),
        ("Pernalonga", "Cenoura"), ("Batman", "Morcego"), ("Homem-Aranha", "Teia"),
        ("As Meninas Superpoderosas", "Açúcar"), ("Ben 10", "Relógio"), ("Phineas e Ferb", "Férias"),
        ("Rick and Morty", "Portal"), ("Sailor Moon", "Prisma"), ("Peppa Pig", "Lama"),
        ("Tartarugas Ninja", "Esgoto"), ("Caverna do Dragão", "Mestre")
    ],
    
    "Personagens da TV e Animação": [
        ("Mickey Mouse", "Orelhas - Estúdio de Animação Clássico"), 
        ("Pato Donald", "Raiva - Estúdio de Animação Clássico"), 
        ("Pateta", "Desastre - Estúdio de Animação Clássico"),
        ("Cinderela", "Sapato - Conto de Fadas"), 
        ("Branca de Neve", "Maçã - Conto de Fadas"), 
        ("Ariel", "Voz - Conto de Fadas"),
        ("Simba", "Rei - Filme de Animação"), 
        ("Aladdin", "Lâmpada - Conto de Fadas"), 
        ("Mulan", "Guerreira - Filme de Animação"),
        ("Peter Pan", "Voar - Conto de Fadas"), 
        ("Fera", "Rosa - Conto de Fadas"), 
        ("Elsa", "Gelo - Animação 3D"),
        ("Moana", "Oceano - Animação 3D"), 
        ("Hércules", "Força - Mitologia Animada"), 
        ("Stitch", "Alienígena - Filme de Animação"),
        ("Woody", "Xerife - Estúdio 3D"), 
        ("Buzz Lightyear", "Espaço - Estúdio 3D"), 
        ("Nemo", "Procurado - Estúdio 3D"),
        ("Dory", "Esquecida - Estúdio 3D"), 
        ("Relâmpago McQueen", "Velocidade - Estúdio 3D"), 
        ("Mike Wazowski", "Olho - Estúdio 3D"),
        ("Sulley", "Pelos - Estúdio 3D"), 
        ("Sr. Incrível", "Força - Estúdio 3D"), 
        ("Wall-E", "Robô - Estúdio 3D"),
        ("Homer Simpson", "Donut - Desenho de TV Adulto"), 
        ("Bob Esponja", "Fritador - Desenho de TV Infantil"), 
        ("Patrick Estrela", "Pedra - Desenho de TV Infantil"),
        ("Pernalonga", "Cenoura - Desenho de TV Clássico"), 
        ("Scooby-Doo", "Mistério - Desenho de TV Clássico"), 
        ("Pica-Pau", "Madeira - Desenho de TV Clássico"),
        ("Goku", "Esferas - Anime de Luta"), 
        ("Naruto", "Ninjas - Anime de Luta"), 
        ("Pikachu", "Choque - Anime de Monstros"),
        ("Ben 10", "Relógio - Desenho de TV"), 
        ("Florzinha", "Líder - Desenho de TV"), 
        ("Dexter", "Laboratório - Desenho de TV"),
        ("Coragem", "Susto - Desenho de TV"), 
        ("Peppa Pig", "Lama - Desenho Infantil"), 
        ("Cosmo", "Desejos - Desenho de TV"),
        ("Phineas", "Invenção - Desenho de TV"), 
        ("Mutano", "Animais - Desenho de TV"), 
        ("Ravena", "Magia - Desenho de TV"),
        ("Fred Flintstone", "Pedreira - Desenho de TV Clássico"), 
        ("George Jetson", "Futuro - Desenho de TV Clássico"), 
        ("Popeye", "Espinafre - Desenho de TV Clássico"),
        ("Garfield", "Lasanha - Desenho de TV"), 
        ("Snoopy", "Casinha - Desenho de TV Clássico"), 
        ("Dick Vigarista", "Trapaça - Desenho de TV Clássico")
    ]
}
