BANCO_PALAVRAS = {
    "Comidas": [
        ("Pizza", "Fatia"), ("Hambúrguer", "Pão"), ("Sushi", "Alga"), ("Lasanha", "Travessa"), ("Churrasco", "Brasa"),
        ("Tacos", "Crosta"), ("Cachorro Quente", "Salsicha"), ("Batata Frita", "Óleo"), ("Salada", "Folha"), ("Sopa", "Caldo"),
        ("Macarrão", "Fio"), ("Arroz", "Grão"), ("Feijão", "Caldo"), ("Bife", "Chapa"), ("Frango Assado", "Espeto"),
        ("Peixe Frito", "Espinha"), ("Camarão", "Casca"), ("Lagosta", "Antena"), ("Omelete", "Ovo"), ("Ovo Frito", "Gema"),
        ("Pão", "Miolo"), ("Queijo", "Cura"), ("Presunto", "Fatia"), ("Salame", "Fio"), ("Mortadela", "Borda"),
        ("Manteiga", "Derretida"), ("Requeijão", "Copo"), ("Iogurte", "Fundo"), ("Leite", "Caixa"), ("Cereal", "Tigela"),
        ("Bolo", "Cobertura"), ("Torta", "Massa"), ("Sorvete", "Cone"), ("Chocolate", "Cacau"), ("Pudim", "Calda"),
        ("Gelatina", "Tremor"), ("Brigadeiro", "Granulado"), ("Beijinho", "Cravo"), ("Quindim", "Gema"), ("Churros", "Doce"),
        ("Maçã", "Pecado"), ("Banana", "Cacho"), ("Laranja", "Bagaço"), ("Uva", "Vinho"), ("Morango", "Semente"),
        ("Melancia", "Casca"), ("Abacaxi", "Coroa"), ("Melão", "Rede"), ("Mamão", "Semente"), ("Pera", "Curva"),
        ("Manga", "Fiapo"), ("Limão", "Azedo"), ("Pêssego", "Caroço"), ("Cereja", "Cabo"), ("Goiaba", "Miolo"),
        ("Maracujá", "Calma"), ("Kiwi", "Pelo"), ("Coco", "Água"), ("Abacate", "Vitamina"), ("Figo", "Árvore"),
        ("Tomate", "Molho"), ("Alface", "Salada"), ("Cebola", "Choro"), ("Alho", "Dente"), ("Cenoura", "Visão"),
        ("Batata", "Terra"), ("Brócolis", "Árvore"), ("Couve", "Refogado"), ("Espinafre", "Força"), ("Pimentão", "Oco"),
        ("Pepino", "Picles"), ("Abobrinha", "Refogado"), ("Berinjela", "Roxo"), ("Milho", "Sabugo"), ("Ervilha", "Vagem"),
        ("Feijão Verde", "Vagem"), ("Lentilha", "Ano"), ("Grão de Bico", "Pasta"), ("Soja", "Proteína"), ("Amendoim", "Casca"),
        ("Nozes", "Quebra"), ("Castanha", "Ouriço"), ("Amêndoa", "Pele"), ("Pistache", "Verde"), ("Avelã", "Creme"),
        ("Pimenta", "Ardor"), ("Sal", "Mar"), ("Açúcar", "Cana"), ("Azeite", "Oliva"), ("Vinagre", "Ácido"),
        ("Mostarda", "Amarelo"), ("Ketchup", "Tomate"), ("Maionese", "Ovo"), ("Molho Shoyu", "Sódio"), ("Pimenta do Reino", "Pó"),
        ("Orégano", "Pizza"), ("Manjericão", "Pesto"), ("Salsa", "Tempero"), ("Cebolinha", "Verde"), ("Coentro", "Tempero")
    ],
    "Animais": [
        ("Cachorro", "Osso"), ("Gato", "Caixa"), ("Rato", "Porão"), ("Leão", "Juba"), ("Tigre", "Listra"),
        ("Urso", "Mel"), ("Lobo", "Uivo"), ("Raposa", "Astúcia"), ("Elefante", "Marfim"), ("Girafa", "Altura"),
        ("Zebra", "Listra"), ("Hipopótamo", "Boca"), ("Rinoceronte", "Chifre"), ("Macaco", "Galho"), ("Gorila", "Peito"),
        ("Chimpanzé", "Ferramenta"), ("Canguru", "Salto"), ("Coala", "Eucalipto"), ("Panda", "Bambu"), ("Camelo", "Deserto"),
        ("Cavalo", "Sela"), ("Vaca", "Leite"), ("Porco", "Lama"), ("Ovelha", "Lã"), ("Cabra", "Montanha"),
        ("Burro", "Carga"), ("Touro", "Arena"), ("Búfalo", "Manada"), ("Alce", "Galhada"), ("Rena", "Neve"),
        ("Galinha", "Grama"), ("Pato", "Lago"), ("Ganso", "Ataque"), ("Peru", "Festa"), ("Pombo", "Praça"),
        ("Corvo", "Agouro"), ("Águia", "Visão"), ("Falcão", "Velocidade"), ("Coruja", "Noite"), ("Papagaio", "Voz"),
        ("Arara", "Cor"), ("Tucano", "Bico"), ("Pinguim", "Gelo"), ("Avestruz", "Velocidade"), ("Pavão", "Elegância"),
        ("Cisne", "Beleza"), ("Gaivota", "Praia"), ("Pelicano", "Bolsa"), ("Cegonha", "Pacote"), ("Flamingo", "Rosa"),
        ("Sapo", "Brejo"), ("Rã", "Pulo"), ("Perereca", "Árvore"), ("Crocodilo", "Rio"), ("Jacaré", "Pântano"),
        ("Tartaruga", "Casco"), ("Jabuti", "Lentidão"), ("Cobra", "Veneno"), ("Lagarto", "Sol"), ("Iguana", "Crista"),
        ("Camaleão", "Disfarce"), ("Dragão de Komodo", "Bactéria"), ("Tubarão", "Focinho"), ("Baleia", "Esguicho"), ("Golfinho", "Aro"),
        ("Foca", "Bola"), ("Leão Marinho", "Orelha"), ("Morsa", "Presa"), ("Peixe", "Escama"), ("Salmão", "Corrente"),
        ("Atum", "Lata"), ("Bacalhau", "Sal"), ("Sardinha", "Lata"), ("Carpa", "Lago"), ("Truta", "Rio"),
        ("Peixe Palhaço", "Anêmona"), ("Cavalo Marinho", "Cauda"), ("Polvo", "Tinta"), ("Lula", "Anel"), ("Água Viva", "Queimadura"),
        ("Estrela do Mar", "Ponta"), ("Caranguejo", "Lado"), ("Lagosta", "Antena"), ("Camarão", "Fritura"), ("Ostra", "Pérola"),
        ("Marisco", "Concha"), ("Caracol", "Rastro"), ("Lesma", "Sal"), ("Minhoca", "Terra"), ("Sanguessuga", "Sangue"),
        ("Aranha", "Teia"), ("Escorpião", "Ferrão"), ("Formiga", "Folha"), ("Abelha", "Mel"), ("Vespa", "Ataque"),
        ("Mosca", "Lixo"), ("Mosquito", "Doença"), ("Borboleta", "Flor"), ("Mariposa", "Luz"), ("Besouro", "Chifre")
    ],
    "Filmes de Sucesso": [
        ("Titanic", "Água"), ("Matrix", "Pílula"), ("Jurassic Park", "Parque"), ("Avatar", "Natureza"), ("Os Vingadores", "Equipe"), 
        ("Star Wars", "Espaço"), ("O Rei Leão", "Realeza"), ("Harry Potter", "Escola"), ("De Volta para o Futuro", "Carro"), ("E.T. O Extraterrestre", "Bicicleta"), 
        ("Tubarão", "Dentes"), ("O Poderoso Chefão", "Família"), ("Gladiador", "Arena"), ("Piratas do Caribe", "Ladrão"), ("Indiana Jones", "Chapéu"), 
        ("Forrest Gump", "Corrida"), ("O Exterminador do Futuro", "Máquina"), ("Clube da Luta", "Regras"), ("A Origem", "Sonho"), ("Interestelar", "Tempo"), 
        ("Psicose", "Banheiro"), ("O Iluminado", "Hotel"), ("Velozes e Furiosos", "Veículo"), ("Rocky", "Escada"), ("Shrek", "Pântano"), 
        ("Toy Story", "Brinquedo"), ("Procurando Nemo", "Busca"), ("Os Incríveis", "Poderes"), ("Coringa", "Riso"), ("O Cavaleiro das Trevas", "Morcego"), 
        ("Homem-Aranha", "Inseto"), ("Pantera Negra", "Gato"), ("Mulher-Maravilha", "Laço"), ("Aquaman", "Oceano"), ("Missão Impossível", "Agente"), 
        ("007 - Cassino Royale", "Espião"), ("O Senhor dos Anéis", "Anel"), ("O Hobbit", "Baixinho"), ("Crepúsculo", "Vampiro"), ("Jogos Vorazes", "Arco"), 
        ("Mad Max", "Deserto"), ("Blade Runner", "Poeira"), ("Alien", "Nave"), ("O Predador", "Monstro"), ("O Exorcista", "Demônio"), 
        ("Invocação do Mal", "Casa"), ("It: A Coisa", "Palhaço"), ("Pânico", "Máscara"), ("Sexta-Feira 13", "Acampamento"), ("Halloween", "Faca")
    ],
    "Marcas Famosas": [
        ("Coca-Cola", "Vermelho"), ("Pepsi", "Azul"), ("Apple", "Fruta"), ("Samsung", "Coreia"), ("Microsoft", "Janela"), 
        ("Google", "Cores"), ("Amazon", "Seta"), ("Netflix", "Tela"), ("Disney", "Castelo"), ("McDonald's", "Amarelo"), 
        ("Burger King", "Coroa"), ("Subway", "Pão"), ("Nike", "Símbolo"), ("Adidas", "Listras"), ("Puma", "Felino"), 
        ("Ferrari", "Cavalo"), ("Porsche", "Escudo"), ("Toyota", "Japão"), ("Volkswagen", "Círculo"), ("Ford", "Oval"), 
        ("BMW", "Hélice"), ("Rolex", "Coroa"), ("Casio", "Pulso"), ("Gucci", "Letras"), ("Louis Vuitton", "Estampa"), 
        ("Prada", "Itália"), ("Zara", "Moda"), ("Chanel", "Elegância"), ("L'Oréal", "Beleza"), ("Gillette", "Lâmina"), 
        ("Colgate", "Sorriso"), ("Pampers", "Bebê"), ("Sony", "Som"), ("Nintendo", "Jogo"), ("PlayStation", "Botões"), 
        ("Xbox", "Caixa"), ("Lego", "Bloco"), ("Mattel", "Brinquedo"), ("Hasbro", "Tabuleiro"), ("Red Bull", "Asas"), 
        ("Heineken", "Estrela"), ("Budweiser", "Cerveja"), ("Nescafé", "Quente"), ("Starbucks", "Sereia"), ("Nestlé", "Pássaro"), 
        ("Visa", "Cartão"), ("Mastercard", "Bolinhas"), ("PayPal", "Dinheiro"), ("Uber", "Viagem"), ("Spotify", "Verde")
    ],
    "Desenhos Famosos": [
        ("Bob Esponja", "Fenda"), ("Os Simpsons", "Amarelo"), ("Pica-Pau", "Risada"), ("Tom e Jerry", "Perseguição"), ("Scooby-Doo", "Biscoito"),
        ("Dragon Ball Z", "Esferas"), ("Naruto", "Vila"), ("Pokémon", "Captura"), ("Os Flintstones", "Pedra"), ("Os Jetsons", "Futuro"),
        ("Pernalonga", "Cenoura"), ("Patolino", "Bico"), ("Batman: A Série Animada", "Morcego"), ("Homem-Aranha", "Teia"), ("X-Men", "Mutantes"),
        ("As Meninas Superpoderosas", "Açúcar"), ("O Laboratório de Dexter", "Gênio"), ("Johnny Bravo", "Topete"), ("Coragem, o Cão Covarde", "Susto"), ("Du, Dudu e Edu", "Bala"),
        ("A Vaca e o Frango", "Bípede"), ("Patrulha Canina", "Resgate"), ("Peppa Pig", "Lama"), ("Hora de Aventura", "Herói"), ("Apenas um Show", "Parque"),
        ("O Incrível Mundo de Gumball", "Gato"), ("Steven Universo", "Joia"), ("Os Jovens Titãs", "Torre"), ("Ben 10", "Relógio"), ("Phineas e Ferb", "Férias"),
        ("Gravity Falls", "Diário"), ("Rick and Morty", "Portal"), ("Futurama", "Entrega"), ("South Park", "Gorro"), ("Uma Família da Pesada", "Sofá"),
        ("Caverna do Dragão", "Mestre"), ("He-Man", "Espada"), ("ThunderCats", "Olho"), ("Cavaleiros do Zodíaco", "Cosmo"), ("Yu-Gi-Oh!", "Duelo"),
        ("Digimon", "Digital"), ("Sailor Moon", "Prisma"), ("Avatar: A Lenda de Aang", "Elemento"), ("A Lenda de Korra", "Equilíbrio"), ("Os Padrinhos Mágicos", "Desejo"),
        ("Jimmy Neutron", "Cérebro"), ("Hey Arnold!", "Cabeça"), ("Doug", "Costelinha"), ("Rugrats: Os Anjinhos", "Fralda"), ("CatDog", "Gêmeos"),
        ("Dora, a Aventureira", "Mochila"), ("Ursinhos Carinhosos", "Nuvem"), ("Smurfs", "Azul"), ("Inspetor Bugiganga", "Casaco"), ("A Pantera Cor-de-Rosa", "Inspeção"),
        ("Popeye", "Espinafre"), ("Garfield", "Lasanha"), ("Snoopy", "Casinha"), ("Zé Colmeia", "Piquenique"), ("Corrida Maluca", "Trapaça"),
        ("Animaniacs", "Torre"), ("Pinky e o Cérebro", "Mundo"), ("Tiny Toon", "Universidade"), ("O Máskara", "Verde"), ("Super Choque", "Eletricidade"),
        ("Liga da Justiça", "Satélite"), ("Tartarugas Ninja", "Esgoto"), ("Três Espiãs Demais", "Agência"), ("Clube das Winx", "Fada"), ("Kim Possible", "Agente"),
        ("Lilo & Stitch", "Experiência"), ("DuckTales", "Cofre"), ("Tico e Teco", "Esquilos"), ("Capitão Planeta", "Anel"), ("A Vida Moderna de Rocko", "Austrália"),
        ("Os Castores Zangados", "Represa"), ("Invasor Zim", "Alienígena"), ("Mansão Foster para Amigos Imaginários", "Amigo"), ("KND: A Turma do Bairro", "Árvore"), ("Billy e Mandy", "Foice"),
        ("Samurai Jack", "Passado"), ("Titio Avô", "Pochete"), ("Ursos Sem Curso", "Pilha"), ("My Little Pony", "Amizade"), ("Star contra as Forças do Mal", "Varinha"),
        ("A Casa Coruja", "Bruxa"), ("As Aventuras de Jackie Chan", "Talismã"), ("X-Men: Evolution", "Instituto"), ("Justiça Jovem", "Equipe"), ("Os Pinguins de Madagascar", "Tática"),
        ("O Fantástico Mundo de Bobby", "Triciclo"), ("Manda-Chuva", "Beco"), ("Dick Vigarista e Mutley", "Medalha"), ("Capitão Caverna", "Clava"), ("O Show da Luna", "Ciência"),
        ("Irmão do Jorel", "Abacate"), ("Turma da Mônica", "Coelhadas"), ("Caillou", "Careca"), ("Transformers", "Disfarce"), ("Miraculous Ladybug", "Joaninha")
    ],
    "Comidas pt.2": [
        ("Hambúrguer", "Pão"), ("Sushi", "Cru"), ("Pizza", "Forno"), ("Lasanha", "Queijo"), ("Feijoada", "Preto"),
        ("Churrasco", "Fogo"), ("Sorvete", "Gelado"), ("Pudim", "Forma"), ("Macarronada", "Massa"), ("Pipoca", "Milho"),
        ("Bolo", "Festa"), ("Coxinha", "Frito"), ("Pastel", "Feira"), ("Tapioca", "Branco"), ("Açaí", "Roxo"),
        ("Risoto", "Arroz"), ("Batata Frita", "Óleo"), ("Brigadeiro", "Panela"), ("Pão de Queijo", "Minas"), ("Strogonoff", "Creme"),
        ("Cachorro-quente", "Salsicha"), ("Croissant", "Meia-lua"), ("Panqueca", "Frigideira"), ("Guacamole", "Abacate"), ("Ceviche", "Limão"),
        ("Paella", "Peixes"), ("Polenta", "Amarelo"), ("Bife à Milanesa", "Empanado"), ("Purê", "Amassado"), ("Empada", "Recheio"),
        ("Kebab", "Espeto"), ("Churros", "Açúcar"), ("Beijinho", "Coco"), ("Pão de Alho", "Churrasqueira"), ("Farofa", "Mistura"),
        ("Vinagrete", "Acompanhamento"), ("Moqueca", "Dendê"), ("Vatapá", "Camarão"), ("Acarajé", "Bahia"), ("Cuscuz", "Nordeste"),
        ("Pamonha", "Palha"), ("Canjica", "Doce"), ("Curau", "Canela"), ("Goiabada", "Goiaba"), ("Mousse", "Aerado"),
        ("Yakisoba", "Ásia"), ("Taco", "Casca"), ("Burrito", "Enrolado"), ("Nachos", "Triângulo"), ("Sopa", "Caldo")
    ],
    "Animais pt.2": [
        ("Cachorro", "Coleira"), ("Gato", "Caixa"), ("Leão", "Juba"), ("Tigre", "Listras"), ("Elefante", "Tromba"),
        ("Girafa", "Pescoço"), ("Urso", "Caverna"), ("Lobo", "Uivo"), ("Porco", "Lama"), ("Vaca", "Pasto"),
        ("Cavalo", "Sela"), ("Galinha", "Penas"), ("Pato", "Lago"), ("Cobra", "Escamas"), ("Jacaré", "Réptil"),
        ("Tartaruga", "Casco"), ("Sapo", "Pulo"), ("Macaco", "Árvore"), ("Morcego", "Noite"), ("Tubarão", "Dentes"),
        ("Baleia", "Oceano"), ("Golfinho", "Salto"), ("Polvo", "Tentáculos"), ("Lula", "Tinta"), ("Camarão", "Antena"),
        ("Caranguejo", "Praia"), ("Aranha", "Teia"), ("Escorpião", "Veneno"), ("Abelha", "Flor"), ("Formiga", "Trabalho"),
        ("Borboleta", "Colorido"), ("Mosquito", "Sangue"), ("Barata", "Esgoto"), ("Besouro", "Casca"), ("Caracol", "Gosma"),
        ("Minhoca", "Terra"), ("Ovelha", "Lã"), ("Raposa", "Astúcia"), ("Rinoceronte", "Chifre"), ("Hipopótamo", "Pesado"),
        ("Zebra", "África"), ("Canguru", "Bolsa"), ("Coala", "Eucalipto"), ("Panda", "Bambu"), ("Gorila", "Forte"),
        ("Coruja", "Visão"), ("Águia", "Garras"), ("Pinguim", "Gelo"), ("Avestruz", "Corre"), ("Camelo", "Deserto")
    ],
    "Personagens pt.2": [
        ("Mickey Mouse", "É o rosto principal de um império gigante - Disney"),
        ("Pato Donald", "Sua paciência é famosa por acabar muito rápido - Disney"),
        ("Pateta", "Costuma causar acidentes sem ter a intenção - Disney"),
        ("Minnie Mouse", "É conhecida por seu estilo e por estar sempre bem acompanhada - Disney"),
        ("Pluto", "Não costuma opinar, apenas acompanha as aventuras dos outros - Disney"),
        ("Cinderela", "Sua vida mudou completamente por causa de um prazo apertado - Disney"),
        ("Branca de Neve", "Confiou na pessoa errada por causa de uma oferta irrecusável - Disney"),
        ("Ariel", "Estava insatisfeita com sua vida e fez um sacrifício enorme para mudar - Disney"),
        ("Simba", "Fugiu do passado por muito tempo antes de encarar seu destino - Disney"),
        ("Aladdin", "Contou com uma ajuda inusitada para fingir ser quem não era - Disney"),
        ("Mulan", "Precisou esconder sua verdadeira identidade para proteger sua família - Disney"),
        ("Peter Pan", "Recusa-se a aceitar a passagem natural do tempo - Disney"),
        ("Fera", "Aprendeu a tratar os outros bem apenas quando ficou sem opções - Disney"),
        ("Elsa", "Isolou-se de todos por medo de machucar quem amava - Disney"),
        ("Moana", "Ignorou as regras impostas para atender ao chamado do oceano - Disney"),
        ("Hércules", "Teve que provar seu valor do zero após perder seus privilégios - Disney"),
        ("Stitch", "Foi criado com um único propósito destrutivo, mas mudou de ideia - Disney"),
        ("Woody", "Lidou muito mal com a sensação de estar sendo substituído - Pixar"),
        ("Buzz Lightyear", "Viveu uma grande ilusão antes de aceitar a própria realidade - Pixar"),
        ("Nemo", "Seu sumiço causou uma movimentação enorme - Pixar"),
        ("Dory", "Sua mente tem dificuldade em reter informações simples - Pixar"),
        ("Relâmpago McQueen", "Precisou ser forçado a desacelerar para entender o que importava - Pixar"),
        ("Mike Wazowski", "Seu parceiro costuma levar todo o crédito pelo trabalho duro - Pixar"),
        ("Sulley", "Sua aparência afasta os outros, mas tem um lado muito dócil - Pixar"),
        ("Sr. Incrível", "Sentia muita falta dos seus antigos dias de glória - Pixar"),
        ("Wall-E", "Fazia um trabalho exaustivo e repetitivo até encontrar um novo propósito - Pixar"),
        ("Batman", "Usa o medo e a riqueza para combater o crime sem ter poderes - DC Comics"),
        ("Superman", "Veio de outro planeta e tem fraqueza por uma pedra verde - DC Comics"),
        ("Homem-Aranha", "Carrega uma culpa enorme após perder uma figura paterna - Marvel"),
        ("Homem de Ferro", "Conseguiu salvar o mundo usando tecnologia própria e muita inteligência - Marvel"),
        ("Capitão América", "Acordou em uma época completamente diferente da sua juventude - Marvel"),
        ("Mulher-Maravilha", "Deixou sua ilha isolada para lidar com o mundo exterior - DC Comics"),
        ("Thor", "Teve que aprender a ser humilde após perder sua principal arma - Marvel"),
        ("Hulk", "Tem sérios problemas quando perde o controle das emoções - Marvel"),
        ("Mario", "Passa a vida inteira correndo atrás de resgates e coletando moedas - Super Mario"),
        ("Sonic", "Tem uma pressa insuportável e odeia ficar parado - Sonic"),
        ("Pikachu", "É pequeno, amarelo e armazena energia nas bochechas - Pokémon"),
        ("Homem-Biscoito", "Foge de ser comido e tem frases muito marcantes - Shrek"),
        ("Gato de Botas", "Usa acessórios de nobreza e faz um olhar irresistível para manipular - Shrek"),
        ("Homer Simpson", "Prioriza comida e descanso acima de qualquer responsabilidade - Os Simpsons"),
        ("Bob Esponja", "Trabalha com culinária rápida e tem uma alegria irritante - Bob Esponja")
    ],
    #"Teste": [
        #("palavra", "dica vaga")
        #]
}
